/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QUANLYBANCAFE.view;

import QUANLYBANCAFE.model.BAN;
import QUANLYBANCAFE.service.BANservice;
import QUANLYBANCAFE.service.KhuVucService;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class EditBanCafe extends javax.swing.JFrame {
    private BAN ban;
    BANservice banservice;
    KhuVucService khuvucservice;
    /**
     * Creates new form EditBanCafe
     */
    public EditBanCafe(int MaBan_ID) {
        initComponents();
        
        banservice = new BANservice();
        ban = banservice.getBanbyID(MaBan_ID);
        khuvucservice = new KhuVucService();
        
        ArrayList<String> listMaKV = khuvucservice.getAllMaKV();
        for(String maKV : listMaKV){
            CBMaKV.addItem(maKV);
        }
        
        txtMaBan.setText(String.valueOf(ban.getMaBan_ID()));
        txtTenBan.setText(String.valueOf(ban.getTenBan()));
        
        String maKV = String.valueOf(ban.getMaKhuVuc_ID());
        for(int i=0; i < CBMaKV.getItemCount(); i++){
            String item = CBMaKV.getItemAt(i);
            if(item.equals(maKV)){
                CBMaKV.setSelectedIndex(i);
                break;
            }
        }
        
        txtMoTa.setText(String.valueOf(ban.getMoTa()));
        
        if (ban.isTrangThai()) {
            onRadioButton.setSelected(true);
        } else {
            offRadioButton.setSelected(true);   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaBan = new javax.swing.JTextField();
        txtTenBan = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        onRadioButton = new javax.swing.JRadioButton();
        offRadioButton = new javax.swing.JRadioButton();
        CBMaKV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Mã Bàn:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Mã KV:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tên Bàn:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mô tả:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Trạng Thái:");

        txtMaBan.setEditable(false);
        txtMaBan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        editButton.setText("Sửa");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(onRadioButton);
        onRadioButton.setText("Đang hoạt động");

        buttonGroup1.add(offRadioButton);
        offRadioButton.setText("Đã rời đi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(editButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(CBMaKV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenBan)
                                .addComponent(txtMoTa, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(onRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(offRadioButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBMaKV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onRadioButton)
                    .addComponent(offRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(editButton))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new JBAN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        String maBanText = txtMaBan.getText();
        String tenBan = txtTenBan.getText();
        String maKVText = String.valueOf(CBMaKV.getSelectedItem());
        String moTa = txtMoTa.getText();

        // Kiểm tra các trường nhập liệu có rỗng không
        if (maBanText.isEmpty() || tenBan.isEmpty() || maKVText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin Mã Bàn, Tên Bàn và Mã Khu Vực!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Chuyển đổi các chuỗi thành số nguyên
            int maBan = Integer.parseInt(maBanText);
            int maKV = Integer.parseInt(maKVText);

            // Tạo đối tượng bàn mới
            ban = new BAN();
            ban.setMaBan_ID(maBan);
            ban.setTenBan(tenBan);
            // Thiết lập trạng thái tùy thuộc vào RadioButton được chọn
            boolean trangThai = false;
            if (onRadioButton.isSelected()) {
                trangThai = true;
            } else if (offRadioButton.isSelected()) {
                trangThai = false;
            }

            ban.setTrangThai(trangThai);

            // Kiểm tra và đặt giá trị cho trường mô tả
            if (moTa.isEmpty()) {
                ban.setMoTa("");
            } else {
                ban.setMoTa(moTa);
            }

            ban.setMaKhuVuc_ID(maKV);

            // Thực hiện cập nhật thông tin của bàn vào cơ sở dữ liệu
            banservice.updateBan(ban);

            // Hiển thị thông báo thành công và xóa dữ liệu nhập trước đó
            JOptionPane.showMessageDialog(this, "Sửa lại bàn thành công!");
            clearFields();

            // Hiển thị frame JBAN
            new JBAN().setVisible(true);
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã Bàn và Mã Khu Vực phải là số nguyên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void clearFields() {
        txtMaBan.setText("");
        txtTenBan.setText("");
        txtMoTa.setText("");
        CBMaKV.setSelectedItem(0);
        onRadioButton.setSelected(false);
        offRadioButton.setSelected(false);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBMaKV;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton offRadioButton;
    private javax.swing.JRadioButton onRadioButton;
    private javax.swing.JTextField txtMaBan;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtTenBan;
    // End of variables declaration//GEN-END:variables
}
